Restore AppCompat themes for some material components (#4811)
We still rely on them for using material views.

```
java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
	at com.google.android.material.progressindicator.BaseProgressIndicatorSpec.<init>(BaseProgressIndicatorSpec.java:92)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:76)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:68)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:63)
	at com.google.android.material.progressindicator.CircularProgressIndicator.createSpec(CircularProgressIndicator.java:87)
	at com.google.android.material.progressindicator.CircularProgressIndicator.createSpec(CircularProgressIndicator.java:58)
	at com.google.android.material.progressindicator.BaseProgressIndicator.<init>(BaseProgressIndicator.java:144)
	at com.google.android.material.progressindicator.CircularProgressIndicator.<init>(CircularProgressIndicator.java:78)
	at com.google.android.material.progressindicator.CircularProgressIndicator.<init>(CircularProgressIndicator.java:73)
	at com.google.android.material.progressindicator.CircularProgressIndicator.<init>(CircularProgressIndicator.java:69)
	at app.lawnchair.views.LauncherPreviewView.<init>(LauncherPreviewView.kt:46)
	at app.lawnchair.backup.ui.CreateBackupViewModel.captureScreenshot(CreateBackupViewModel.kt:58)
	at app.lawnchair.backup.ui.CreateBackupViewModel.access$captureScreenshot(CreateBackupViewModel.kt:24)
	at app.lawnchair.backup.ui.CreateBackupViewModel$1.invokeSuspend(CreateBackupViewModel.kt:38)
```