Fix Crash on A9 - LC14 (#3871)
* Fix Crash on A9 - LC14 (#1)

* Update VibratorWrapper.java

* Update VibratorWrapper.java

* Update RecentsAnimationDeviceState.java

* Update MotionEventsUtils.java

* Update NoButtonQuickSwitchTouchController.java

* Update MotionEventsUtils.java

* Update Workspace.java

* Update NoButtonQuickSwitchTouchController.java

Remove added check no longer needed

* Update MotionEventsUtils.java

* Update Workspace.java

remove extra check added just now

* Update ApiWrapper.java

fix this issue when when changing the number of lines and columns of home screen grid

```
error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method getActivityOverrides()Ljava/util/Map; in class Landroid/content/pm/LauncherApps; or its super classes (declaration of 'android.content.pm.LauncherApps' appears in /system/framework/framework.jar)
	at com.android.launcher3.uioverrides.ApiWrapper.getActivityOverrides(ApiWrapper.java:55)
	at com.android.launcher3.AutoInstallsLayout.<init>(AutoInstallsLayout.java:208)
	at com.android.launcher3.AutoInstallsLayout.<init>(AutoInstallsLayout.java:187)
	at com.android.launcher3.DefaultLayoutParser.<init>(DefaultLayoutParser.java:57)
	at com.android.launcher3.model.ModelDbController.getDefaultLayoutParser(ModelDbController.java:494)
	at com.android.launcher3.model.ModelDbController.loadDefaultFavoritesIfNecessary(ModelDbController.java:396)
	at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(LoaderTask.java:376)
	at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:348)
	at app.lawnchair.views.LauncherPreviewView$loadModelData$1.run(LauncherPreviewView.kt:101)
	at app.lawnchair.views.LauncherPreviewView.loadModelData(LauncherPreviewView.kt:111)
	at app.lawnchair.views.LauncherPreviewView.$r8$lambda$9n1GudRhfMpYAkR1-vecefjJG-A(Unknown Source:0)
	at app.lawnchair.views.LauncherPreviewView$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```